### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Nairdaa** [EvanIMK/Shavit-Race#2]
Hello,

Since shavit's has it's own text formatting api, could you please get rid of stuff like https://github.com/EvanIMK/Shavit-Race/commit/483bf66a958cb64ba6180610f3b64f7489a4e231#diff-47ae591dab790cf2e0cf898421d11f10R10 and let people use their own Timer colours?

gS_ChatStrings <- this stuff

**Comment by EvanChrisp** [comment]
6745ec620a9325b55b741ccf7e88726ebc2501b4
