### ISSUE TITLE
[Bug] Wont Compile

### ISSUE THREAD

**Issue by stunslave** [EvanIMK/Shavit-Race#7]
![image](https://user-images.githubusercontent.com/47533535/134460570-ed0fd04b-68f3-46d0-b9e9-a1e988c55237.png)
Shown in Image.

**Comment by Nairdaa** [comment]
It compiles just fine even with the newest includes. 

> Compiling source finished!
> User opened a new file: F:\steamcmd\css\cstrike\addons\sourcemod\scripting\include\shavit.inc
> Compiling source started!
>     SourcePawn Compiler 1.10.0.6492
>     Copyright (c) 1997-2006 ITB CompuPhase
>     Copyright (c) 2004-2018 AlliedModders LLC
>     
>     Code size:            20516 bytes
>     Data size:           135588 bytes
>     Stack/heap size:      16384 bytes
>     Total requirements:  172488 bytes
>     
>     Saved compiled source: F:\steamcmd\css\cstrike\addons\sourcemod\scripting\compiled\shavit-challenge.smx
> Compiling source finished!
>

**Comment by Nairdaa** [comment]
Oh, yes, shavit.inc is not in the package. I blame @EvanIMK

**Comment by Nairdaa** [comment]
https://github.com/EvanIMK/Shavit-Race/pull/8
Grab this file and the plugin is going to compile like a charm

**Comment by EvanIMK** [comment]
8ab6d8c84a26c61d11a79b198ac1a8b701a8e9c3
